// Question Type
export const RECIEVE_QUESTION_TYPES = 'RECIEVE_QUESTION_TYPES'
export const QUESTION_TYPES_FAILURE = 'QUESTION_TYPES_FAILURE'
export const QUESTION_TYPES_SUCCESS = 'QUESTION_TYPES_SUCCESS'
// Authentication
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER'
// user
export const RECIEVE_USERS = 'RECIEVE_USERS'
export const USERS_FAILURE = 'USERS_FAILURE'
export const USERS_SUCCESS = 'USERS_SUCCESS'
