//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/1/2017 6:19:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace DotVueCore.Data.Models
{
    public partial class CategoriesPost {

        public CategoriesPost()
        {
            OnCreated();
        }

        public virtual int CategoryId
        {
            get;
            set;
        }

        public virtual int PostId
        {
            get;
            set;
        }

        public virtual Post Post
        {
            get;
            set;
        }

        public virtual Category Category
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CategoriesPost toCompare = obj as CategoriesPost;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CategoryId, toCompare.CategoryId))
            return false;
          if (!Object.Equals(this.PostId, toCompare.PostId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CategoryId.GetHashCode();
          hashCode = (hashCode * 7) + PostId.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
