//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/1/2017 6:19:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace DotVueCore.Data.Models
{
    public partial class Post {

        public Post()
        {
            this.CategoriesPosts = new List<CategoriesPost>();
            this.Comments = new List<Comment>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Discriminator
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string Text
        {
            get;
            set;
        }

        public virtual System.Nullable<int> PostedAt
        {
            get;
            set;
        }

        public virtual System.Nullable<int> BlogId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> UserId
        {
            get;
            set;
        }

        public virtual IList<CategoriesPost> CategoriesPosts
        {
            get;
            set;
        }

        public virtual IList<Comment> Comments
        {
            get;
            set;
        }

        public virtual Blog Blog
        {
            get;
            set;
        }

        public virtual User User
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
