//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/7/2017 7:10:28 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using DotVueCore.Data.Models;

namespace DotVueCore.Data.Models
{
    public partial class User {

        public User()
        {
            this.IsLocked = false;
            this.EmailConfirmed = false;
            this.PhoneNumberConfirmed = false;
            this.TwoFactorEnabled = false;
            this.LockoutEnabled = false;
            this.AccessFailedCount = 0;
            this.TimeZone = 81m;
            this.Mode = 1;
            this.SiteId = 1;
            this.HasTaeCert = false;
            this.HasVocational = false;
            this.IsDownloadMoa = false;
            this.IsShowStartUp = true;
            this.IsAcceptTerm = false;
            this.IsDoneInduction = false;
            this.ActivityLogs = new List<ActivityLog>();
            this.AvetmisEnrollments = new List<AvetmisEnrollment>();
            this.Envets = new List<Envet>();
            this.Evidences = new List<Evidence>();
            this.LearnerInfos = new List<LearnerInfo>();
            this.LearnerPostAddressInfos = new List<LearnerPostAddressInfo>();
            this.OrganizationUsers = new List<OrganizationUser>();
            this.RtoUsers = new List<RtoUser>();
            this.StudentClassInfos = new List<StudentClassInfo>();
            this.StudentNotes = new List<StudentNote>();
            this.TrainerClassInfos = new List<TrainerClassInfo>();
            this.UserAddressInfos = new List<UserAddressInfo>();
            this.UserClaims = new List<UserClaim>();
            this.UserDocuments = new List<UserDocument>();
            this.UserLogins = new List<UserLogin>();
            this.UserQualifications = new List<UserQualification>();
            this.UserRoles = new List<UserRole>();
            OnCreated();
        }

        public virtual long Id
        {
            get;
            set;
        }

        public virtual string Login
        {
            get;
            set;
        }

        public virtual string Email
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> ApprovalDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> LastLoginDate
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> IsLocked
        {
            get;
            set;
        }

        public virtual string PasswordQuestion
        {
            get;
            set;
        }

        public virtual string PasswordAnswer
        {
            get;
            set;
        }

        public virtual string ActivationToken
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> EmailConfirmed
        {
            get;
            set;
        }

        public virtual string SecurityStamp
        {
            get;
            set;
        }

        public virtual string PhoneNumber
        {
            get;
            set;
        }

        public virtual string MobileNumber
        {
            get;
            set;
        }

        public virtual string WorkPhoneNumber
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> PhoneNumberConfirmed
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> TwoFactorEnabled
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> LockoutEndDateUtc
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> LockoutEnabled
        {
            get;
            set;
        }

        public virtual System.Nullable<int> AccessFailedCount
        {
            get;
            set;
        }

        public virtual System.Nullable<long> UserTypeId
        {
            get;
            set;
        }

        public virtual string TitleName
        {
            get;
            set;
        }

        public virtual string FirstName
        {
            get;
            set;
        }

        public virtual string LastName
        {
            get;
            set;
        }

        public virtual string Sex
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual string Address
        {
            get;
            set;
        }

        public virtual string Photo
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> Dob
        {
            get;
            set;
        }

        public virtual string Bio
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> TimeZone
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> ExpiryDate
        {
            get;
            set;
        }

        public virtual System.Nullable<int> Mode
        {
            get;
            set;
        }

        public virtual System.Nullable<long> CreatedBy
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }

        public virtual System.Nullable<long> LastModifiedBy
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }

        public virtual System.Nullable<long> DeletedBy
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> DeletedDate
        {
            get;
            set;
        }

        /// <summary>
        /// 1=Admin,2=RTO,3=Organization,4=Trainer,5=Assesser,6=Learner
        /// </summary>
        public virtual System.Nullable<int> SiteId
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> HasTaeCert
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> HasVocational
        {
            get;
            set;
        }

        /// <summary>
        /// For Admin Organization
        /// </summary>
        public virtual System.Nullable<bool> IsDownloadMoa
        {
            get;
            set;
        }

        /// <summary>
        /// For Admin Organization
        /// </summary>
        public virtual System.Nullable<bool> IsShowStartUp
        {
            get;
            set;
        }

        /// <summary>
        /// FOR Organization
        /// </summary>
        public virtual System.Nullable<bool> IsAcceptTerm
        {
            get;
            set;
        }

        /// <summary>
        /// For Accessor/Trainner
        /// </summary>
        public virtual System.Nullable<bool> IsDoneInduction
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> StudentRegistrationInfoSentDate
        {
            get;
            set;
        }

        public virtual IList<ActivityLog> ActivityLogs
        {
            get;
            set;
        }

        public virtual IList<AvetmisEnrollment> AvetmisEnrollments
        {
            get;
            set;
        }

        public virtual IList<Envet> Envets
        {
            get;
            set;
        }

        public virtual IList<Evidence> Evidences
        {
            get;
            set;
        }

        public virtual IList<LearnerInfo> LearnerInfos
        {
            get;
            set;
        }

        public virtual IList<LearnerPostAddressInfo> LearnerPostAddressInfos
        {
            get;
            set;
        }

        public virtual IList<OrganizationUser> OrganizationUsers
        {
            get;
            set;
        }

        public virtual IList<RtoUser> RtoUsers
        {
            get;
            set;
        }

        public virtual IList<StudentClassInfo> StudentClassInfos
        {
            get;
            set;
        }

        public virtual IList<StudentNote> StudentNotes
        {
            get;
            set;
        }

        public virtual IList<TrainerClassInfo> TrainerClassInfos
        {
            get;
            set;
        }

        public virtual IList<UserAddressInfo> UserAddressInfos
        {
            get;
            set;
        }

        public virtual IList<UserClaim> UserClaims
        {
            get;
            set;
        }

        public virtual IList<UserDocument> UserDocuments
        {
            get;
            set;
        }

        public virtual IList<UserLogin> UserLogins
        {
            get;
            set;
        }

        public virtual IList<UserQualification> UserQualifications
        {
            get;
            set;
        }

        public virtual IList<UserRole> UserRoles
        {
            get;
            set;
        }

        public virtual UserType UserType
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
